language: ruby
rvm:
- 2.1.0
- ruby-head
addons:
  code_climate:
    repo_token: 80336b2292acc1d2838cc43c583642601efa411f78917a5bd257ee8233a7de1d
script: bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: Pyn7uwqx45RdSPLmQpPrfqpkcfJ7Dog1pRyVWKtd4h+ExbF8EReewJGjqCcEJImKVywAAG5k6bkP8UgMWSnBIg+nIuVefpndSlJyQgil5tlAGWwwarqKohrixhTn1M/UWiGBxd3Nn4Yvb+sCIWnCcqBeXMTFkDyfNm7U2qtXTxk=
  gem: rrimm
  on:
    tags: true
    repo: kamaradclimber/rrimm
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
